### ISSUE TITLE
Remover vty-ui

### ISSUE THREAD

**Issue by asakeron** [haskellbr/workhs#2]
`vty-ui` foi depreciado. Podemos usar alguma coisa mais simples e `cheapskate-terminal` para exibir texto.

**Comment by yamadapc** [comment]
Feito no `master`. Um detalhe: para fazer parsing de sinais como as teclas de setas, o `list-prompt` agora usa o `vty`. Isso foi triste para mim e adiciona um tamanho razoável no binário. Talvez valha a pena migrar totalmente para o `brick`.

Outro detalhe é que o `cheapskate-terminal` precisa fazer wrapping do texto. Isso necessita uma mudança +/- estrutural, porque o pretty-printer hoje não faz ideia do resto do estado.

Há duas soluções que vejo para isso:
- Usar o `vty-ui` com um formatter de texto que faça o wrapping e lide com os atributos e jogar fora o uso do `ansi-terminal` (estimei que o `vty-ui` adiciona por volta de 10MB no binário)
- Usar o [`ansi-terminal-builder`](https://github.com/yamadapc/ansi-terminal-builder) que estou escrevendo para montar facilitar a construção de listas de `(Text, [SGR])` e processar o output todo em um ponto no final

Estou pendendo para a segunda opção, mas vamos ver como vai ser. Não ajuda que o `vty-ui` está sendo deprecado e que o `brick` não tem essa feature de wrapping.
